[project]
name = "hello-node"
version = "0.0.4"
description = "A simple Hello Node application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.10",
]
