name: Pylint

on: [push]

env:
  uv-version: latest

jobs:
  lint-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - run: ls -al ./.github/workflows
    - uses: ./.github/workflows/setup.yml
      with:
        uv-version: ${{ env.uv-version }}
        python-version: ${{ matrix.python-version }}
    - name: lint
      run: uvx ruff $(git ls-files '*.py')
  lint-requirements:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/setup.yml
      with:
        uv-version: ${{ env.uv-version }}
        python-version: ${{ matrix.python-version }}
    - name: lint requirements
      run: |
        uv export --no-dev --format requirements.txt > requirements.txt.tmp
        git diff requirements.txt requirements.txt.tmp
