name: ci
on: [push]

env:
  UV_VERSION: latest
  IMAGE_NAME: ${{ github.repository }}


jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - name: "Install UV"
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ env.UV_VERSION }}
        enable-cache: true
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    - name: run ruff
      run: uvx ruff check $(git ls-files '*.py')
  lint-requirements:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - name: "Install UV"
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ env.UV_VERSION }}
        enable-cache: true
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    - name: lint requirements
      run: |
        uv export --no-dev --format requirements.txt > requirements.txt.tmp
        git diff requirements.txt requirements.txt.tmp

  docker-build:
    needs: [lint-python, lint-requirements]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the docker image
        run: docker build . --file Dockerfile  --tag ${{ env.IMAGE_NAME }}:${{ github.sha }}
