name: ci
on: [push]

env:
  UV_VERSION: latest
  IMAGE_NAME: ${{ github.repository }}


jobs:
  lint-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-uv
      with:
        python-version: ${{ matrix.python-version }}
        uv-version: ${{ env.UV_VERSION }}
    - name: run ruff
      run: uvx ruff check $(git ls-files '*.py')
  lint-requirements:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-uv
      with:
        python-version: ${{ matrix.python-version }}
        uv-version: ${{ env.UV_VERSION }}
    - name: lint requirements
      run: |
        uv export --no-dev --format requirements.txt > requirements.txt.tmp
        git diff requirements.txt requirements.txt.tmp

  docker-build:
    needs: [lint-python, lint-requirements]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the docker image
        run: docker build . --file Dockerfile  --tag ${{ env.IMAGE_NAME }}:${{ github.sha }}
